services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5500:80"
    volumes:
      - ./containers-data/postgres:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
      
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongoDB/containers-data/mongodb:/data/db

  php-apache:
    build: .
    container_name: php_apache_container
    volumes:
    - ./website:/var/www/html
    ports:
    - "8000:80"
    depends_on:
    - postgres
    environment:
      PHP_POSTGRES_HOST: postgres
      PHP_POSTGRES_DB: postgres
      PHP_POSTGRES_USER: admin
      PHP_POSTGRES_PASSWORD: password
      PHP_EXTENSIONS: pgsql, pdo_pgsql


volumes:
  postgres_data:
  pgadmin_data:
